version: '3'
services:
  nats:
    image: nats:2.10.22
    container_name: nats
    ports:
      - '4222:4222'
      - '8222:8222'   # Monitoring port (optional)
    networks:
      - dev_propeller-network
    command: ["-js"]  # Enable JetStream
  redis:
    image: 'bitnami/redis:6.2.7'
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - dev_propeller-network
  propeller:
    build:
      context: ../..
      dockerfile: Dockerfile
    container_name: propeller
    environment:
      - PROPELLER_BROKER_REDIS_ADDRESS=redis:6379
      - PROPELLER_BROKER_NATS_URL=nats:4222
      - PROPELLER_CONFIG_FILE_PATH=/etc
    ports:
      - "8081:8081"
      - "5011:5011"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8081" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure
    networks:
      - dev_propeller-network
networks:
  dev_propeller-network:
    external: false
