title: propeller
description: propeller is an opinionated push platform for realtime streaming between clients (mobile apps) and backend services
remote_theme: just-the-docs/just-the-docs
#theme: just-the-docs

url: https://cred-club.github.io/
baseurl: /propeller

